export const ADMIN_ROUTE = '/admin'
export const CART_ROUTE = '/cart'
export const LOGIN_ROUTE = '/login'
export const HOME_ROUTE = '/home'
export const PRODUCT_ROUTE = '/product'
export const REGISTRATION_ROUTE = '/registration'
export const USER_ROUTE = '/user'